"""Generate env.sh and openclaw.json files from config.yaml."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = PROJECT_ROOT / "config.yaml"
ENV_SH_PATH = PROJECT_ROOT / "env.sh"
IMAGES_DIR = PROJECT_ROOT / "workflow" / "images"

MODEL_DEFAULTS = {
    "reasoning": False,
    "input": ["text"],
    "cost": {"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
    "contextWindow": 384000,
    "maxTokens": 384000,
}


def load_config() -> dict:
    if not CONFIG_PATH.exists():
        print(f"[ERROR] config.yaml not found at {CONFIG_PATH}")
        print("  Run: cp config.example.yaml config.yaml")
        sys.exit(1)

    with open(CONFIG_PATH) as f:
        cfg = yaml.safe_load(f)

    errors = []
    if not cfg.get("providers"):
        errors.append("'providers' section is required")
    if not cfg.get("roles"):
        errors.append("'roles' section is required")

    for role_name in ("pair", "judge", "ipi"):
        role = (cfg.get("roles") or {}).get(role_name)
        if not role:
            if role_name == "judge":
                errors.append("roles.judge is required (used for llm_judge grading)")
            continue
        if not role.get("base_url"):
            errors.append(f"roles.{role_name}.base_url is required")
        if not role.get("api_key"):
            errors.append(f"roles.{role_name}.api_key is required")
        if not role.get("model"):
            errors.append(f"roles.{role_name}.model is required")

    for pid, prov in (cfg.get("providers") or {}).items():
        if not prov.get("base_url"):
            errors.append(f"providers.{pid}.base_url is required")
        if not prov.get("api_key"):
            errors.append(f"providers.{pid}.api_key is required")
        if not prov.get("models"):
            errors.append(f"providers.{pid}.models is required (at least one model)")
        for m in prov.get("models") or []:
            if not m.get("id"):
                errors.append(f"providers.{pid}: each model needs an 'id' field")

    if errors:
        print("[ERROR] config.yaml validation failed:")
        for e in errors:
            print(f"  - {e}")
        sys.exit(1)

    return cfg


def generate_env_sh(cfg: dict) -> None:
    roles = cfg["roles"]
    settings = cfg.get("settings", {})

    lines = [
        "#!/bin/bash",
        "# Auto-generated by scripts/generate_config.py — do not edit manually",
        "",
    ]

    web_sim = settings.get("web_sim_base_url", "http://openblog.com")
    lines.append(f'export WEB_SIM_BASE_URL="{web_sim}"')
    lines.append("")

    role_env_map = {
        "pair": "PAIR_LLM",
        "judge": "JUDGE_LLM",
        "ipi": "IPI_LLM",
    }

    for role_name, env_prefix in role_env_map.items():
        role = roles.get(role_name)
        if not role:
            continue
        lines.append(f'export {env_prefix}_BASE_URL="{role["base_url"]}"')
        lines.append(f'export {env_prefix}_API_KEY="{role["api_key"]}"')
        lines.append(f'export {env_prefix}_MODEL="{role["model"]}"')
        lines.append("")

    ENV_SH_PATH.write_text("\n".join(lines))
    print(f"  Generated: {ENV_SH_PATH.relative_to(PROJECT_ROOT)}")


def _slugify_alias(provider_id: str, model_id: str) -> str:
    raw = f"{provider_id}/{model_id}"
    return (
        raw.replace("/", ".")
        .replace("_", ".")
        .replace("-", ".")
        .replace(" ", ".")
        .lower()
    )


def _build_openclaw_json(cfg: dict) -> dict:
    providers_out = {}

    for pid, prov in cfg["providers"].items():
        provider_entry: dict = {
            "baseUrl": prov["base_url"],
            "apiKey": prov["api_key"],
        }
        if prov.get("api"):
            provider_entry["api"] = prov["api"]

        models_out = []
        for m in prov["models"]:
            model_entry: dict = {"id": m["id"]}
            model_entry["name"] = m.get("name", f'{m["id"]} (Custom Provider)')
            if m.get("api"):
                model_entry["api"] = m["api"]
            model_entry["reasoning"] = m.get("reasoning", MODEL_DEFAULTS["reasoning"])
            model_entry["input"] = m.get("input", MODEL_DEFAULTS["input"])
            model_entry["cost"] = m.get("cost", MODEL_DEFAULTS["cost"])
            model_entry["contextWindow"] = m.get(
                "context_window", MODEL_DEFAULTS["contextWindow"]
            )
            model_entry["maxTokens"] = m.get(
                "max_tokens", MODEL_DEFAULTS["maxTokens"]
            )
            models_out.append(model_entry)

        provider_entry["models"] = models_out
        providers_out[pid] = provider_entry

    # Build agent model aliases
    model_aliases = {}
    first_model_full_id = None
    for pid, prov in cfg["providers"].items():
        for m in prov["models"]:
            full_id = f"{pid}/{m['id']}"
            alias = _slugify_alias(pid, m["id"])
            model_aliases[full_id] = {"alias": alias}
            if first_model_full_id is None:
                first_model_full_id = full_id

    result = {
        "models": {"mode": "merge", "providers": providers_out},
        "agents": {
            "defaults": {
                "model": {"primary": first_model_full_id or ""},
                "models": model_aliases,
            }
        },
        "tools": {"profile": "full"},
    }

    return result


def generate_openclaw_jsons(cfg: dict) -> None:
    base_config = _build_openclaw_json(cfg)

    if not IMAGES_DIR.exists():
        print(f"  [WARN] {IMAGES_DIR} not found, skipping openclaw.json generation")
        return

    variant_dirs = sorted(
        d
        for d in IMAGES_DIR.iterdir()
        if d.is_dir()
        and not d.name.startswith(".")
        and (d / "Dockerfile").exists()
    )

    for variant_dir in variant_dirs:
        overrides_path = variant_dir / "openclaw.overrides.json"
        merged = json.loads(json.dumps(base_config))

        if overrides_path.exists():
            with open(overrides_path) as f:
                overrides = json.load(f)
            merged.update(overrides)

        out_path = variant_dir / "openclaw.json"
        with open(out_path, "w") as f:
            json.dump(merged, f, indent=2, ensure_ascii=False)
            f.write("\n")

        print(f"  Generated: {out_path.relative_to(PROJECT_ROOT)}")


def main() -> None:
    print("[INFO] Loading config.yaml...")
    cfg = load_config()

    print("[INFO] Generating env.sh...")
    generate_env_sh(cfg)

    print("[INFO] Generating openclaw.json for image variants...")
    generate_openclaw_jsons(cfg)

    print("[SUCCESS] All configuration files generated.")


if __name__ == "__main__":
    main()
